Adjusting Templates

diff --git a/templates/mediawiki-infrastructure.template b/templates/mediawiki-infrastructure.template
--- a/templates/mediawiki-infrastructure.template
+++ b/templates/mediawiki-infrastructure.template
@@ -562,6 +562,7 @@ Resources:
   ECSAutoScalingGroup:
     Condition: CreateECSCluster
     Type: AWS::AutoScaling::AutoScalingGroup
+    DependsOn: ["MountTargetA", "MountTargetB" ]
     Properties:
       VPCZoneIdentifier: !Ref 'ECSSubnets'
       LaunchConfigurationName: !Ref 'ECSLaunchConfiguration'
@@ -597,7 +598,7 @@ Resources:
         Fn::Sub: '#!/bin/bash
 
           # Install Helpers
-          yum install -y aws-cfn-bootstrap
+          yum install -y aws-cfn-bootstrap nfs-utils jq
 
           # Run Config Sets
           /opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName}
@@ -635,6 +636,62 @@ Resources:
 
                   ${Param1}', {Param1: !Sub 'action=/opt/aws/bin/cfn-init -v --region
                     ${AWS::Region} --stack ${AWS::StackName} --resource ECSLaunchConfiguration'}]
+            /tmp/mount-efs.sh:
+              mode: "000755"
+              content : !Sub |
+                #!/bin/bash
+
+                EFS_REGION=${AWS::Region}
+                EFS_MOUNT_DIR=/mnt/efs
+                EFS_FILE_SYSTEM_ID=${EFSFileSystem}
+
+                echo "Mounting EFS filesystem ${EFSFileSystem} to directory ${EFS_MOUNT_DIR} ..."
+
+                echo 'Stopping NFS ID Mapper...'
+                service rpcidmapd status &> /dev/null
+                if [ $? -ne 0 ] ; then
+                    echo 'rpc.idmapd is already stopped!'
+                else
+                    service rpcidmapd stop
+                    if [ $? -ne 0 ] ; then
+                        echo 'ERROR: Failed to stop NFS ID Mapper!'
+                        exit 1
+                    fi
+                fi
+
+                echo 'Checking if EFS mount directory exists...'
+                if [ ! -d ${EFS_MOUNT_DIR} ]; then
+                    echo "Creating directory ${EFS_MOUNT_DIR} ..."
+                    mkdir -p ${EFS_MOUNT_DIR}
+                    if [ $? -ne 0 ]; then
+                        echo 'ERROR: Directory creation failed!'
+                        exit 1
+                    fi
+                else
+                    echo "Directory ${EFS_MOUNT_DIR} already exists!"
+                fi
+
+                mountpoint -q ${EFS_MOUNT_DIR}
+                if [ $? -ne 0 ]; then
+                    echo "mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${EFS_FILE_SYSTEM_ID}.efs.${EFS_REGION}.amazonaws.com:/ ${EFS_MOUNT_DIR}"
+                    mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${EFS_FILE_SYSTEM_ID}.efs.${EFS_REGION}.amazonaws.com:/ ${EFS_MOUNT_DIR}
+                    if [ $? -ne 0 ] ; then
+                        echo 'ERROR: Mount command failed!'
+                        exit 1
+                    fi
+                    chmod 777 ${EFS_MOUNT_DIR}
+                    runuser -l  ec2-user -c "touch ${EFS_MOUNT_DIR}/it_works"
+                    if [[ $? -ne 0 ]]; then
+                        echo 'ERROR: Permission Error!'
+                        exit 1
+                    else
+                        runuser -l  ec2-user -c "rm -f ${EFS_MOUNT_DIR}/it_works"
+                    fi
+                else
+                    echo "Directory ${EFS_MOUNT_DIR} is already a valid mountpoint!"
+                fi
+
+                echo 'EFS mount complete.'
           services:
             sysvinit:
               cfn-hup:
